name: authServer
version: 0.0.1
description: A server to handle logins for the CoU Client
author: CoU Development Team

dependencies:
  redstone: any
  redstone_mapper_pg: any
  http: any
  uuid: any
  args: any
dev_dependencies:
  unittest: any