name: authServer
version: 0.0.1
description: A server to handle logins for the CoU Client
author: CoU Development Team

dependencies:
  redstone: any
  redstone_mapper_pg: any
  http: any
  uuid: any
  args: any
  mailer: ">=0.8.12 <0.9.0"
  path: "^1.3.5"

dev_dependencies:
  unittest: any