name: authServer
version: 0.0.1
description: A server to handle logins for the CoU Client
author: CoU Development Team

dependencies:
  redstone: "^0.6.2"
  redstone_mapper_pg: "0.2.0-beta.2+2"
  http: "^0.11.3+3"
  uuid: "^0.5.0"
  args: "^0.13.2"
  mailer: "^1.0.0"
  path: "^1.3.9"

dev_dependencies:
  test: "^0.12.6+2"