name: authServer
version: 0.0.1
description: A server to handle logins for the CoU Client
author: CoU Development Team

dependencies:
  redstone: any
  redstone_mapper_pg: any
  http: any
  uuid: any
  args: any
  async_await:
    git: https://github.com/dart-lang/async_await.git
  mailer: ">=0.8.12 <0.9.0"
dev_dependencies:
  unittest: any
transformers:
- async_await